name: deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.18.2"
      - run: npm install --frozen-lockfile
      - run: npm run build
      - run: npm run type:check
      - run: npm run test
      - name: Publish to NPM
        if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
        uses: botpress/gh-actions/publish-if-not-exists@master
        with:
          path: "."
          token: "${{ secrets.NPM_ACCESS_TOKEN }}"
